### ISSUE TITLE
Allow other devs to use the cluster that you've made.

### ISSUE THREAD

**Issue by MiDo-kun** [dejwid/mern-blog#1]
Hi there!
I just want to remind I guess?? Mainly because I can't access the collections or the DB itself using the URI when connecting to MongoDB Atlas. Just wondering if you set the IP whitelisted so far? Can you check it and allow different IP's to access the db itself. Thanks, have a nice day.

**Comment by Joshwawo** [comment]
Hello, in this project a free mongod atlas database was used, it was deleted after finishing it, you can get a free cluster in  https://www.mongodb.com/atlas/database , and if you upload the api to a hosting, change these lines of code.
```
//If you don't want to have any problems with CORS, change these lines of code, keep in mind that anyone can make calls to the API, without getting the CORS error.

- app.use(cors({credentials:true,origin:'http://localhost:3000'}));

+ app.use(cors());
```

**Comment by MiDo-kun** [comment]
Oh thanks highly appreciated.
